name: Generate Datas

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  
  # Permite executar o workflow manualmente a qualquer momento
  workflow_dispatch:

  # Executa a cada push na branch master/main
  push:
    branches:
    - master
    - main

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    # IMPORTANTE: Permissão para o bot commitar a imagem no seu repositório
    permissions:
      contents: write
    
    steps:
      # Verifica o repositório
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Gera a animação da cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: andreluiscode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Envia os arquivos gerados para a branch 'output'
      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
